author: "Nguyễn Văn Bảy"
maked_at: "© 2019"
VALID_EMAIL_REGEX: !ruby/regexp '/\A[a-zA-Z0-9_\.]+\z/i'
max_username: 200
min_password: 3
min_name: 1
max_name: 100
min_phone: 3
max_phone: 25
min_address: 3
max_address: 250
num_user: 10
url_avata: "https://bootdey.com/img/Content/user_1.jpg"
theme_config: "twitter-bootstrap-4"
num_product: 10
unit: "VND"
num_combo_product: 10
num_combo: 10
min_name_product: 3
max_name_product: 250
min_name_combo: 3
max_name_combo: 250
num_table: 10
min_number_table: 3
max_number_table: 250
url_table: "http://www.interstatecashregister.com/wp-content/uploads/2017/06/Table-Service-icon.png"
num_table_order: 18
bg_green: "bg-green"
bg_red: "bg-red"
bg_blue: "bg-blue"
status_bill: "active"
count_auto: 1
rezo: 0
selected_product: "product"
selected_combo: "combo"
status_update: 0
single_chair: "single_chair"
double_chair: "double_chair"
four_chair: "four_chair"
eight_chair: "four_chair"
unactive: "unactive"
number_in_page: 10
allowed: "allowed"
unallowed: "unallowed"
start: 1
